#!/usr/bin/env pwsh

# Install all VSCode extensions from the list
code --install-extension 4ops.terraform
code --install-extension aaron-bond.better-comments
code --install-extension albert.tabout
code --install-extension bierner.markdown-mermaid
code --install-extension bradlc.vscode-tailwindcss
code --install-extension burkeholland.simple-react-snippets
code --install-extension christian-kohler.npm-intellisense
code --install-extension dbaeumer.vscode-eslint
code --install-extension denoland.vscode-deno
code --install-extension dsznajder.es7-react-js-snippets
code --install-extension ecmel.vscode-html-css
code --install-extension formulahendry.auto-rename-tag
code --install-extension formulahendry.code-runner
code --install-extension foxundermoon.shell-format
code --install-extension github.vscode-pull-request-github
code --install-extension golang.go
code --install-extension grapecity.gc-excelviewer
code --install-extension hediet.vscode-drawio
code --install-extension henoc.svgeditor
code --install-extension janisdd.vscode-edit-csv
code --install-extension jock.svg
code --install-extension laurencebahiirwa.deno-std-lib-snippets
code --install-extension mattlott.copy-github-url
code --install-extension mechatroner.rainbow-csv
code --install-extension mikestead.dotenv
code --install-extension mindaro-dev.file-downloader
code --install-extension ms-azuretools.vscode-azureresourcegroups
code --install-extension ms-azuretools.vscode-containers
code --install-extension ms-azuretools.vscode-docker
code --install-extension ms-python.black-formatter
code --install-extension ms-python.debugpy
code --install-extension ms-python.isort
code --install-extension ms-python.python
code --install-extension ms-python.vscode-pylance
code --install-extension ms-python.vscode-python-envs
code --install-extension ms-vscode-remote.remote-containers
code --install-extension ms-vscode-remote.remote-ssh
code --install-extension ms-vscode-remote.remote-ssh-edit
code --install-extension ms-vscode.live-server
code --install-extension ms-vscode.makefile-tools
code --install-extension ms-vscode.remote-explorer
code --install-extension ms-vsliveshare.vsliveshare
code --install-extension neonxp.gotools
code --install-extension pkief.material-icon-theme
code --install-extension pollywoggames.pico8-ls
code --install-extension pranaygp.vscode-css-peek
code --install-extension pucelle.vscode-css-navigation
code --install-extension quicktype.quicktype
code --install-extension recoiljs-snippets.recoiljs-snippets
code --install-extension redhat.vscode-commons
code --install-extension redhat.vscode-xml
code --install-extension redhat.vscode-yaml
code --install-extension rogalmic.bash-debug
code --install-extension shakram02.bash-beautify
code --install-extension shd101wyy.markdown-preview-enhanced
code --install-extension steoates.autoimport
code --install-extension streetsidesoftware.code-spell-checker
code --install-extension timonwong.shellcheck
code --install-extension tomoki1207.pdf
code --install-extension unifiedjs.vscode-mdx
code --install-extension vitaliymaz.vscode-svg-previewer
code --install-extension william-voyek.vscode-nginx
code --install-extension yoavbls.pretty-ts-errors
code --install-extension yzhang.markdown-all-in-one
code --install-extension zhuangtongfa.material-theme
